Alias /mapserver-tutorial/ "/ms4w/apps/mapserver-tutorial/"

<Directory "/ms4w/apps/mapserver-tutorial/">
  AllowOverride None
  Options Indexes FollowSymLinks Multiviews 
  Order allow,deny
  Allow from all
</Directory>
