Alias /openlayers/ "/ms4w/apps/openlayers-dev/"

<Directory "/ms4w/apps/openlayers-dev">
  AllowOverride None
  Options Indexes FollowSymLinks Multiviews 
  Order allow,deny
  Allow from all
</Directory>
